version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install build dependencies for the package
      - apt-get update
      - apt-get install -y build-essential
      - apt-get install -y libomp-dev
    post_install:
      # Install the package itself for autodoc
      - python -m pip install .

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

formats:
  - pdf
  - epub
